version: '3.7'

services:
  mysql:
    image: mysql:5.7.32
    restart: always
    container_name: mysql
    hostname: mysql
    volumes:
      - /var/lib/mysql:/var/lib/mysql
    env_file:
      - ./mysql.env
    networks:
      - glpi

  glpi:
    image: ## Image name ##
    restart: always
    container_name : glpi
    hostname: glpi
    ports:
      - "80:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/www/html/glpi/:/var/www/html/glpi
    environment:
      - TIMEZONE=Europe/Moscow
    networks:
      - glpi

    networks:
      glpi:
        external: true